# Generated by Django 2.1.5 on 2022-11-09 21:19

import brands.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[brands.validators.validate_date]),
        ),
    ]
